[package]
name = "tgrep"
version = "0.1.0"
authors = ["Dmytro Milinevskyi <dmilinevskyi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicli = "0.4"
structopt = "0.2"
glob = "0.3"
lazy_static = "1.4"
regex = "1"
ansi_term = "0.12"